apiVersion: v1
kind: Service
metadata:
  name: arj-test
  labels:
    app: hello-world
    tier: backend
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
  - port: 8080
    nodePort: 32028
  selector:
    app: hello-world
    tier: backend